### ISSUE TITLE
add skia license

### ISSUE THREAD

**Issue by anthrotype** [khaledhosny/skia-pathops#1]

**Comment by khaledhosny** [comment]
We now have the full Skia repository as submodule, or do you want it at top level directory? (I wonder if symbolic link from the submodule would work?).

**Comment by anthrotype** [comment]
well, we will still need a license file of our own.

**Comment by anthrotype** [comment]
i think it's enough that the submodule contains the whole tree including its own license file.
for the license of the python wrapper, I don't know. You choose

**Comment by khaledhosny** [comment]
Lets just use the same license for simplicity (and if Skia is ever re-licensed we should remember to update ours 🙂).

**Comment by anthrotype** [comment]
sgtm
